version: "2"

services:
  rng:
    build: rng
    ports:
    - "8001:8080"

  hasher:
    build: hasher
    ports:
    - "8002:8080"

  webui:
    build: webui
    ports:
    - "8000:80"
    volumes:
    - "./webui/files/:/files/"
    links:
     - redis

  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
    - "6379:6379"

  worker:
    build: worker
    links:
     - redis

