#pull base image
FROM openjdk:8-jdk-alpine

#maintainer 
MAINTAINER dev.asadriaz@gmail.com



#default command
CMD java -jar /data/com.worker.service-0.0.1-SNAPSHOT.jar

#copy hello world to docker image
ADD ./data/com.worker.service-0.0.1-SNAPSHOT.jar /data/com.worker.service-0.0.1-SNAPSHOT.jar